Feat/phrase
JandirHabitzreuter/WhatRemember pull request #18
Opened 2023-04-14 01:07 UTC by JandirHabitzreuter

* Created phrase module with controller, service and swagger documentation
* Excluded old fonts

2023-04-18 02:25 UTC, AliandroK approved these changes
Approve

2023-04-18 23:56 UTC, dodocarlos requested changes
Nice work! I left some suggestions

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/dto/Phrase.dto.ts
> +  @IsString()
Since we are using @IsUUID() we don't need to have @IsString() here

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/dto/Phrase.dto.ts
> +      required: false,
Are you using `prettier`? The format seems to be broken here

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/dto/Phrase.dto.ts
> +      })
```suggestion
    @ApiProperty({
      enum: Rating_Phrase,
      required: true,
      description: 'The rating of the phrase',
      example: 'EASY',
    })
```

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/dto/create-phrase.dto.ts
> +    })
```suggestion
  @ApiProperty({
    enum: Rating_Phrase,
    required: true,
    description: 'The rating of the phrase',
    example: 'EASY',
  })
```

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/dto/update-phrase.dto.ts
> +      })
```suggestion
    @ApiProperty({
      enum: Rating_Phrase,
      required: true,
      description: 'The rating of the phrase',
      example: 'EASY',
    })
```

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/entities/phrase.entity.ts
> +export class Phrase {}
We dont need this file. Can you remove it please?

2023-04-18 23:56 UTC, dodocarlos commented on backEnd/src/phrases/phrases.controller.ts
> +@Controller('phrases')
duplicated controller annotation

2023-04-19 00:14 UTC, dodocarlos approved these changes

2023-04-19 00:14 UTC, merged